# 1단계: 빌드 스테이지
FROM gradle:8.4.0-jdk17 AS builder
WORKDIR /app

COPY . .
RUN gradle build -x test

# 2단계: 실행 스테이지
FROM openjdk:17-jdk-slim
WORKDIR /appgit

# JAR 복사
COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]